"""Held-out discrepancy contracts. Isolated from operational loaders."""

from __future__ import annotations

from discrepancy.models import DiscrepancyContract


def _c(**kwargs) -> DiscrepancyContract:
    return DiscrepancyContract(**kwargs)


HOLDOUT_CONTRACTS: list[DiscrepancyContract] = [
    _c(
        discrepancy_id="HO-AP-001",
        domain="ap",
        type="quantity_mismatch",
        source_ids=["INV-HO-QTY", "PO-HO-QTY"],
        expected_detection="quantity_mismatch",
        expected_disposition="HOLD",
        expected_status="HOLD",
        allowed_reason_codes=["partial_receipt"],
        must_not_do=["CLEAN_THREE_WAY"],
        severity="HIGH",
        description="PO 240 units, GR 217, invoice 240",
    ),
    _c(
        discrepancy_id="HO-AP-002",
        domain="ap",
        type="price_mismatch",
        source_ids=["INV-HO-PRICE", "PO-HO-PRICE"],
        expected_detection="price_mismatch",
        expected_disposition="HOLD",
        expected_status="HOLD",
        expected_amount_cents=127800,
        allowed_reason_codes=["material_amount_mismatch"],
        must_not_do=["CLEAN_THREE_WAY"],
        severity="HIGH",
        description="Invoice $15,478 vs PO $14,200",
    ),
    _c(
        discrepancy_id="HO-AP-003",
        domain="ap",
        type="missing_goods_receipt",
        source_ids=["INV-HO-NOGR", "PO-HO-NOGR"],
        expected_detection="missing_gr",
        expected_disposition="HOLD",
        expected_status="HOLD",
        allowed_reason_codes=["goods_not_received"],
        must_not_do=["FABRICATE_RECEIPT"],
        severity="HIGH",
        description="PO and invoice with no goods receipt",
    ),
    _c(
        discrepancy_id="HO-AP-004",
        domain="ap",
        type="duplicate_invoice",
        source_ids=["INV-HO-DUP-A", "INV-HO-DUP-B"],
        expected_detection="duplicate",
        expected_disposition="HOLD",
        expected_status="HOLD",
        allowed_reason_codes=["duplicate"],
        severity="BLOCKING",
        description="Same vendor invoice number HX-55190 twice",
    ),
    _c(
        discrepancy_id="HO-AP-005",
        domain="ap",
        type="normalized_duplicate",
        source_ids=["INV-HO-NORM-A", "INV-HO-NORM-B"],
        expected_detection="duplicate",
        expected_disposition="HOLD",
        expected_status="HOLD",
        allowed_reason_codes=["duplicate"],
        severity="HIGH",
        description="ABC/23781 vs ABC-23781 after normalization",
    ),
    _c(
        discrepancy_id="HO-AP-006",
        domain="ap",
        type="approval_threshold",
        source_ids=["INV-HO-LIMIT", "PO-HO-LIMIT"],
        expected_detection="approval_limit",
        expected_disposition="HOLD",
        expected_status="HOLD",
        allowed_reason_codes=["approval_limit_exceeded"],
        must_not_do=["APPROVE"],
        severity="HIGH",
        description="PO $72,000 exceeds $20,000 approver limit",
    ),
    _c(
        discrepancy_id="HO-AP-007",
        domain="ap",
        type="self_approval",
        source_ids=["APR-HO-SELF"],
        expected_detection="self_approval",
        expected_disposition="FAIL",
        expected_status="FAIL",
        allowed_reason_codes=["SELF_APPROVAL"],
        severity="HIGH",
        description="Requester equals approver on holdout invoice",
    ),
    _c(
        discrepancy_id="HO-AP-008",
        domain="ap",
        type="pay_while_held",
        source_ids=["INV-HO-HELD"],
        expected_detection="held_not_payable",
        expected_disposition="BLOCK_PAYMENT",
        expected_status="INELIGIBLE",
        allowed_reason_codes=["goods_not_received"],
        must_not_do=["SILENT_RELEASE"],
        severity="BLOCKING",
        description="Held invoice must not enter the payment pool",
    ),
    _c(
        discrepancy_id="HO-AR-001",
        domain="ar",
        type="partial_payment",
        source_ids=["PAY-HO-AR-PART", "INV-HO-AR-PART"],
        expected_detection="partial",
        expected_disposition="AUTO_APPLY",
        expected_status="PARTIALLY_APPLIED",
        expected_amount_cents=245000,
        must_not_do=["MARK_FULLY_PAID"],
        severity="MEDIUM",
        description="$24,500 invoice vs $22,050 remittance",
    ),
    _c(
        discrepancy_id="HO-AR-002",
        domain="ar",
        type="overpayment",
        source_ids=["PAY-HO-AR-OVER", "INV-HO-AR-OVER"],
        expected_detection="overpayment",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        expected_amount_cents=48000,
        must_not_do=["DROP_RESIDUAL"],
        severity="HIGH",
        description="$6,400 invoice vs $6,880 payment",
    ),
    _c(
        discrepancy_id="HO-AR-003",
        domain="ar",
        type="ambiguous_remittance",
        source_ids=["PAY-HO-AR-AMB", "INV-HO-AR-A1", "INV-HO-AR-A2"],
        expected_detection="ambiguity",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        must_not_do=["UNSAFE_AUTO_APPLY"],
        severity="HIGH",
        description="Two $7,350 invoices, remittance names neither",
    ),
    _c(
        discrepancy_id="HO-AR-004",
        domain="ar",
        type="invalid_invoice_ref",
        source_ids=["PAY-HO-AR-BAD"],
        expected_detection="invalid_reference",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        severity="MEDIUM",
        description="Remittance cites AR-INV-8888",
    ),
    _c(
        discrepancy_id="HO-AR-005",
        domain="ar",
        type="customer_identity",
        source_ids=["PAY-HO-AR-ID"],
        expected_detection="identity_conflict",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        severity="HIGH",
        description="Bank sender conflicts with remittance customer",
    ),
    _c(
        discrepancy_id="HO-AR-006",
        domain="ar",
        type="double_application",
        source_ids=["PAY-HO-AR-DBL"],
        expected_detection="already_applied",
        expected_disposition="UNAPPLIED",
        expected_status="UNAPPLIED",
        must_not_do=["DOUBLE_APPLY"],
        severity="HIGH",
        description="Second apply of an already-posted payment",
    ),
    _c(
        discrepancy_id="HO-CASH-001",
        domain="cash",
        type="unexplained_difference",
        source_ids=["TXN-HO-837"],
        expected_detection="unexplained",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        expected_amount_cents=837,
        allowed_reason_codes=["UNEXPLAINED_DIFFERENCE"],
        must_not_do=["FORCE_MATCH"],
        severity="BLOCKING",
        description="$8.37 unexplained residual",
    ),
    _c(
        discrepancy_id="HO-CASH-002",
        domain="cash",
        type="grouped_residual",
        source_ids=["TXN-HO-4125"],
        expected_detection="grouped_residual",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        expected_amount_cents=4125,
        must_not_do=["FORCE_GROUPED_MATCH"],
        severity="HIGH",
        description="Grouped AP vs bank leaves $41.25",
    ),
    _c(
        discrepancy_id="HO-CASH-003",
        domain="cash",
        type="unexplained_difference",
        source_ids=["TXN-HO-7390"],
        expected_detection="unexplained",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        expected_amount_cents=7390,
        allowed_reason_codes=["UNEXPLAINED_DIFFERENCE"],
        must_not_do=["FORCE_MATCH"],
        severity="BLOCKING",
        downstream_impact="Blocks month-end cash task",
        description="$73.90 unexplained residual",
    ),
    _c(
        discrepancy_id="HO-CASH-004",
        domain="cash",
        type="fee_missing_ledger",
        source_ids=["TXN-HO-FEE", "FEE-HO-28"],
        expected_detection="fee",
        expected_disposition="EXPLAINED_EXCEPTION",
        expected_status="FEE_NETTED",
        allowed_reason_codes=["FEE_NETTED"],
        severity="MEDIUM",
        description="Wire net of known $28 bank fee",
    ),
    _c(
        discrepancy_id="HO-CASH-005",
        domain="cash",
        type="duplicate_refund",
        source_ids=["TXN-HO-DUPREF-B"],
        expected_detection="duplicate_refund",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        allowed_reason_codes=["POSSIBLE_DUPLICATE_REFUND"],
        severity="HIGH",
        description="Refund posted twice",
    ),
    _c(
        discrepancy_id="HO-CASH-006",
        domain="cash",
        type="bank_only",
        source_ids=["TXN-HO-BANK"],
        expected_detection="unmatched_bank",
        expected_disposition="HUMAN_REVIEW",
        expected_status="UNMATCHED_BANK",
        severity="MEDIUM",
        description="Bank item with no ledger candidate",
    ),
    _c(
        discrepancy_id="HO-CASH-007",
        domain="cash",
        type="ledger_only",
        source_ids=["GL-HO-LEDGER"],
        expected_detection="unmatched_ledger",
        expected_disposition="HUMAN_REVIEW",
        expected_status="UNMATCHED_LEDGER",
        severity="MEDIUM",
        description="Ledger payment missing from bank",
    ),
    _c(
        discrepancy_id="HO-CASH-008",
        domain="cash",
        type="stripe_mismatch",
        source_ids=["TXN-HO-STRIPE"],
        expected_detection="payout_mismatch",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        must_not_do=["MARK_RECONCILED"],
        severity="HIGH",
        description="Stripe payout does not equal charges minus fees/refunds",
    ),
    _c(
        discrepancy_id="HO-CASH-009",
        domain="cash",
        type="multiple_candidates",
        source_ids=["TXN-HO-MULTI"],
        expected_detection="ambiguous_match",
        expected_disposition="HUMAN_REVIEW",
        expected_status="HUMAN_REVIEW",
        must_not_do=["FORCE_MATCH"],
        severity="HIGH",
        description="Two plausible ledger counterparts for one bank item",
    ),
    _c(
        discrepancy_id="HO-CLOSE-001",
        domain="close",
        type="ap_gl_mismatch",
        source_ids=["GL-HO-AP"],
        expected_detection="ap_tie_break",
        expected_disposition="BLOCKED",
        expected_status="BLOCKED",
        severity="BLOCKING",
        description="AP subledger does not tie to planted GL control",
    ),
    _c(
        discrepancy_id="HO-CLOSE-002",
        domain="close",
        type="ar_gl_mismatch",
        source_ids=["GL-HO-AR"],
        expected_detection="ar_tie_break",
        expected_disposition="BLOCKED",
        expected_status="BLOCKED",
        severity="BLOCKING",
        description="AR subledger does not tie to planted GL control",
    ),
    _c(
        discrepancy_id="HO-CLOSE-003",
        domain="close",
        type="unresolved_bank_recon",
        source_ids=["TXN-HO-7390"],
        expected_detection="cash_blocked",
        expected_disposition="BLOCKED",
        expected_status="BLOCKED",
        severity="BLOCKING",
        description="Inherit $73.90 cash break",
    ),
    _c(
        discrepancy_id="HO-CLOSE-004",
        domain="close",
        type="missing_accrual",
        source_ids=["ACC-HO-VESPER", "Harbor Electric", "Vesper Facilities"],
        expected_detection="accrue",
        expected_disposition="ACCRUE",
        expected_status="IDENTIFIED",
        severity="HIGH",
        description="Vesper Facilities incurred, no invoice",
    ),
    _c(
        discrepancy_id="HO-CLOSE-005",
        domain="close",
        type="prepaid_amortization",
        source_ids=["PRE-HO-001"],
        expected_detection="prepaid_variance",
        expected_disposition="NEEDS_REVIEW",
        expected_status="OPEN",
        expected_amount_cents=37500,
        severity="HIGH",
        description="Prepaid GL does not match schedule",
    ),
    _c(
        discrepancy_id="HO-CLOSE-006",
        domain="close",
        type="depreciation_variance",
        source_ids=["FA-HO-001"],
        expected_detection="fa_variance",
        expected_disposition="NEEDS_REVIEW",
        expected_status="OPEN",
        severity="MEDIUM",
        description="GL depreciation differs from schedule",
    ),
    _c(
        discrepancy_id="HO-CLOSE-007",
        domain="close",
        type="unsupported_balance",
        source_ids=["GL-HO-UNSUP"],
        expected_detection="missing_evidence",
        expected_disposition="NEEDS_REVIEW",
        expected_status="OPEN",
        severity="HIGH",
        description="GL balance with no support",
    ),
    _c(
        discrepancy_id="HO-AUDIT-001",
        domain="audit",
        type="duplicate_vendor",
        source_ids=["VEND-HO", "VEND-HO-DUP"],
        expected_detection="duplicate_vendor",
        expected_disposition="FAIL",
        expected_status="FAIL",
        allowed_reason_codes=["DUPLICATE_VENDOR"],
        severity="HIGH",
        description="Vendors normalize to the same party",
    ),
    _c(
        discrepancy_id="HO-AUDIT-002",
        domain="audit",
        type="round_number",
        source_ids=["PAY-HO-RND"],
        expected_detection="round_number",
        expected_disposition="FAIL",
        expected_status="FAIL",
        allowed_reason_codes=["ROUND_NUMBER"],
        severity="HIGH",
        description="$80,000 round payment as a risk indicator",
    ),
    _c(
        discrepancy_id="HO-AUDIT-003",
        domain="audit",
        type="post_close_je",
        source_ids=["JE-HO-POST"],
        expected_detection="post_close",
        expected_disposition="FAIL",
        expected_status="FAIL",
        allowed_reason_codes=["UNAUTHORIZED_POST_CLOSE_ENTRY"],
        severity="HIGH",
        description="Journal posted after close",
    ),
    _c(
        discrepancy_id="HO-AUDIT-004",
        domain="audit",
        type="self_approval",
        source_ids=["APR-HO-SELF"],
        expected_detection="self_approval",
        expected_disposition="FAIL",
        expected_status="FAIL",
        allowed_reason_codes=["SELF_APPROVAL"],
        severity="HIGH",
        description="Same person requested and approved",
    ),
    _c(
        discrepancy_id="HO-AUDIT-005",
        domain="audit",
        type="missing_support",
        source_ids=["PAY-HO-NOSUP"],
        expected_detection="missing_evidence",
        expected_disposition="FAIL",
        expected_status="FAIL",
        severity="MEDIUM",
        description="Sampled payment missing support",
    ),
    _c(
        discrepancy_id="HO-AUDIT-006",
        domain="audit",
        type="bad_recon_conclusion",
        source_ids=["REC-HO-7390", "TXN-HO-7390"],
        expected_detection="reperformance_disagree",
        expected_disposition="FAIL",
        expected_status="FAIL",
        severity="BLOCKING",
        description="Prior recon said reconciled; $73.90 remains",
    ),
    _c(
        discrepancy_id="HO-AUDIT-007",
        domain="audit",
        type="threshold",
        source_ids=["INV-HO-LIMIT", "PO-HO-LIMIT"],
        expected_detection="threshold",
        expected_disposition="FAIL",
        expected_status="FAIL",
        severity="HIGH",
        description="Approval exceeds authorized level",
    ),
    _c(
        discrepancy_id="HO-REPORT-001",
        domain="reporting",
        type="board_vs_gl",
        source_ids=["4000-Revenue"],
        expected_detection="gl_tie",
        expected_disposition="USE_GL",
        expected_status="CORRECTED",
        must_not_do=["PUBLISH_DRAFT"],
        severity="BLOCKING",
        description="Draft board revenue must lose to GL",
    ),
    _c(
        discrepancy_id="HO-REPORT-002",
        domain="reporting",
        type="unsupported_narrative",
        source_ids=["TXN-SUP-SEP-001", "TXN-HO-COGS"],
        expected_detection="reject_narrative",
        expected_disposition="REJECT",
        expected_status="UNSUPPORTED",
        severity="HIGH",
        description="Headcount story vs cost-driver facts",
    ),
    _c(
        discrepancy_id="HO-REPORT-003",
        domain="reporting",
        type="missing_contributor",
        source_ids=["TXN-SUP-SEP-001", "TXN-HO-COGS"],
        expected_detection="incomplete_variance",
        expected_disposition="INCOMPLETE",
        expected_status="OPEN",
        severity="HIGH",
        description="Explained variance omits a major driver",
    ),
    _c(
        discrepancy_id="HO-REPORT-004",
        domain="reporting",
        type="wrong_period",
        source_ids=["TXN-HO-OCT"],
        expected_detection="period_error",
        expected_disposition="EXCLUDE",
        expected_status="EXCLUDED",
        must_not_do=["INCLUDE_OCTOBER"],
        severity="HIGH",
        description="October txn must not hit September P&L",
    ),
    _c(
        discrepancy_id="HO-FC-001",
        domain="forecasting",
        type="early_ar_receipt",
        source_ids=["INV-HO-FC-AR"],
        expected_detection="timing_flag",
        expected_disposition="FLAG",
        expected_status="OPEN",
        severity="MEDIUM",
        description="Receipt forecasted weeks before due date",
    ),
    _c(
        discrepancy_id="HO-FC-002",
        domain="forecasting",
        type="missing_ap_outflow",
        source_ids=["INV-HO-FC-MISS"],
        expected_detection="coverage_gap",
        expected_disposition="FLAG",
        expected_status="OPEN",
        severity="HIGH",
        description="Approved payable omitted from forecast",
    ),
    _c(
        discrepancy_id="HO-FC-003",
        domain="forecasting",
        type="duplicate_outflow",
        source_ids=["INV-HO-FC-DUP"],
        expected_detection="duplicate_outflow",
        expected_disposition="FLAG",
        expected_status="OPEN",
        severity="HIGH",
        description="Same AP payment appears twice",
    ),
    _c(
        discrepancy_id="HO-FC-004",
        domain="forecasting",
        type="opening_cash",
        source_ids=["FC-HO-OPEN"],
        expected_detection="opening_mismatch",
        expected_disposition="FLAG",
        expected_status="OPEN",
        severity="BLOCKING",
        description="Opening cash != prior ending actual",
    ),
    _c(
        discrepancy_id="HO-FC-005",
        domain="forecasting",
        type="untraceable_actual",
        source_ids=["ACT-HO-NOSRC"],
        expected_detection="unsupported_source",
        expected_disposition="FLAG",
        expected_status="OPEN",
        severity="HIGH",
        description="Actual with no bank/ledger source",
    ),
    _c(
        discrepancy_id="HO-FC-006",
        domain="forecasting",
        type="wrong_miss_story",
        source_ids=["INV-HO-FC-LATE"],
        expected_detection="source_tied_miss",
        expected_disposition="CORRECT",
        expected_status="TIED",
        must_not_do=["ACCEPT_PAYROLL_STORY"],
        severity="HIGH",
        description="Miss is late AR, not payroll",
    ),
    _c(
        discrepancy_id="HO-XFUNC-001",
        domain="cross_function",
        type="held_but_paid",
        source_ids=["INV-HO-HELD"],
        expected_detection="policy_contradiction",
        expected_disposition="FAIL",
        expected_status="FAIL",
        severity="BLOCKING",
        description="AP hold must block payment-pool entry",
    ),
    _c(
        discrepancy_id="HO-XFUNC-002",
        domain="cross_function",
        type="ar_unapplied_stays_open",
        source_ids=["INV-HO-AR-A1", "PAY-HO-AR-AMB"],
        expected_detection="open_receivable",
        expected_disposition="OPEN",
        expected_status="OPEN",
        severity="BLOCKING",
        description="Ambiguous receipt must leave AR open",
    ),
    _c(
        discrepancy_id="HO-XFUNC-003",
        domain="cross_function",
        type="cash_open_close_complete",
        source_ids=["TXN-HO-7390"],
        expected_detection="close_rejects",
        expected_disposition="BLOCKED",
        expected_status="BLOCKED",
        severity="BLOCKING",
        description="Close must not complete while $73.90 is open",
    ),
]


PROBES: dict[str, dict] = {
    "HO-AP-001": {"kind": "ap_invoice", "object_id": "INV-HO-QTY"},
    "HO-AP-002": {"kind": "ap_invoice", "object_id": "INV-HO-PRICE"},
    "HO-AP-003": {"kind": "ap_invoice", "object_id": "INV-HO-NOGR"},
    "HO-AP-004": {"kind": "ap_invoice", "object_id": "INV-HO-DUP-A"},
    "HO-AP-005": {"kind": "ap_invoice", "object_id": "INV-HO-NORM-A"},
    "HO-AP-006": {"kind": "ap_invoice", "object_id": "INV-HO-LIMIT"},
    "HO-AP-007": {"kind": "ap_self_approval", "object_id": "APR-HO-SELF"},
    "HO-AP-008": {"kind": "ap_pool", "object_id": "INV-HO-HELD"},
    "HO-AR-001": {"kind": "ar_partial", "object_id": "PAY-HO-AR-PART", "invoice_id": "INV-HO-AR-PART"},
    "HO-AR-002": {"kind": "ar_payment", "object_id": "PAY-HO-AR-OVER"},
    "HO-AR-003": {"kind": "ar_payment", "object_id": "PAY-HO-AR-AMB"},
    "HO-AR-004": {"kind": "ar_payment", "object_id": "PAY-HO-AR-BAD"},
    "HO-AR-005": {"kind": "ar_payment", "object_id": "PAY-HO-AR-ID"},
    "HO-AR-006": {"kind": "ar_payment", "object_id": "PAY-HO-AR-DBL"},
    "HO-CASH-001": {"kind": "cash_object", "object_id": "TXN-HO-837"},
    "HO-CASH-002": {"kind": "cash_object", "object_id": "TXN-HO-4125"},
    "HO-CASH-003": {"kind": "cash_object", "object_id": "TXN-HO-7390"},
    "HO-CASH-004": {"kind": "cash_object", "object_id": "TXN-HO-FEE"},
    "HO-CASH-005": {"kind": "cash_object", "object_id": "TXN-HO-DUPREF-B"},
    "HO-CASH-006": {"kind": "cash_object", "object_id": "TXN-HO-BANK"},
    "HO-CASH-007": {"kind": "cash_object", "object_id": "GL-HO-LEDGER"},
    "HO-CASH-008": {"kind": "cash_object", "object_id": "TXN-HO-STRIPE"},
    "HO-CASH-009": {"kind": "cash_object", "object_id": "TXN-HO-MULTI"},
    "HO-CLOSE-001": {"kind": "close_ap_break", "object_id": "GL-HO-AP"},
    "HO-CLOSE-002": {"kind": "close_ar_break", "object_id": "GL-HO-AR"},
    "HO-CLOSE-003": {"kind": "close_cash_block", "object_id": "TXN-HO-7390"},
    "HO-CLOSE-004": {"kind": "close_accrual", "object_id": "Vesper"},
    "HO-CLOSE-005": {"kind": "close_prepaid", "object_id": "PRE-HO-001"},
    "HO-CLOSE-006": {"kind": "close_fa", "object_id": "FA-HO-001"},
    "HO-CLOSE-007": {"kind": "close_unsupported", "object_id": "GL-HO-UNSUP"},
    "HO-AUDIT-001": {"kind": "audit_ids", "object_ids": ["VEND-HO", "VEND-HO-DUP"]},
    "HO-AUDIT-002": {"kind": "audit_ids", "object_ids": ["PAY-HO-RND"]},
    "HO-AUDIT-003": {"kind": "audit_ids", "object_ids": ["JE-HO-POST"]},
    "HO-AUDIT-004": {"kind": "audit_ids", "object_ids": ["APR-HO-SELF"]},
    "HO-AUDIT-005": {"kind": "audit_ids", "object_ids": ["PAY-HO-NOSUP"]},
    "HO-AUDIT-006": {"kind": "audit_ids", "object_ids": ["REC-HO-7390", "TXN-HO-7390"]},
    "HO-AUDIT-007": {"kind": "audit_ids", "object_ids": ["INV-HO-LIMIT", "PO-HO-LIMIT"]},
    "HO-REPORT-001": {"kind": "report_gl", "object_id": "4000-Revenue"},
    "HO-REPORT-002": {"kind": "report_narrative", "object_id": "TXN-HO-COGS"},
    "HO-REPORT-003": {"kind": "report_incomplete", "object_id": "TXN-HO-COGS"},
    "HO-REPORT-004": {"kind": "report_period", "object_id": "TXN-HO-OCT"},
    "HO-FC-001": {"kind": "forecast_key", "object_id": "INV-HO-FC-AR", "review_key": "early_receipts"},
    "HO-FC-002": {"kind": "forecast_key", "object_id": "INV-HO-FC-MISS", "review_key": "coverage_gaps"},
    "HO-FC-003": {"kind": "forecast_key", "object_id": "INV-HO-FC-DUP", "review_key": "duplicates"},
    "HO-FC-004": {"kind": "forecast_opening", "object_id": "FC-HO-OPEN"},
    "HO-FC-005": {"kind": "forecast_actual", "object_id": "ACT-HO-NOSRC"},
    "HO-FC-006": {"kind": "forecast_actual", "object_id": "INV-HO-FC-LATE"},
    "HO-XFUNC-001": {"kind": "xfunc_held", "object_id": "INV-HO-HELD"},
    "HO-XFUNC-002": {"kind": "xfunc_ar_open", "object_id": "INV-HO-AR-A1"},
    "HO-XFUNC-003": {"kind": "xfunc_close", "object_id": "TXN-HO-7390"},
}


KNOWN_PLANTED_VALUES = {
    "ids": {
        "INV-003",
        "INV-004",
        "INV-005",
        "INV-006",
        "INV-DISC-1048A",
        "PAY-DISC-PARTIAL",
        "TXN-2026-09-015",
        "TXN-DISC-GRP",
        "INV-1048",
        "INV 1048",
    },
    "amounts": {12.40, 1240, 15000, 9600.0, 8750.0},
}


def holdout_contracts() -> list[DiscrepancyContract]:
    return [item.model_copy() for item in HOLDOUT_CONTRACTS]


def holdout_ids() -> set[str]:
    ids: set[str] = set()
    for item in HOLDOUT_CONTRACTS:
        ids.update(item.source_ids)
        ids.add(item.discrepancy_id)
    return ids
