"""Machine-readable detection contracts. Not loaded by operational workflows."""

from __future__ import annotations

from discrepancy.models import DiscrepancyContract


def _c(**kwargs) -> DiscrepancyContract:
    return DiscrepancyContract(**kwargs)


CONTRACTS: list[DiscrepancyContract] = [
    _c(discrepancy_id="AP-DISC-001", domain="ap", type="quantity_mismatch", source_ids=["INV-003", "PO-103"], expected_detection="quantity_mismatch", expected_disposition="HOLD", expected_status="HOLD", allowed_reason_codes=["partial_receipt"], must_not_do=["CLEAN_THREE_WAY"], severity="HIGH", downstream_impact="Cannot pay as a clean match", description="Invoice 100 units vs receipt 90"),
    _c(discrepancy_id="AP-DISC-002", domain="ap", type="price_mismatch", source_ids=["INV-004", "PO-105"], expected_detection="price_mismatch", expected_disposition="HOLD", expected_status="HOLD", expected_amount_cents=62500, allowed_reason_codes=["material_amount_mismatch"], must_not_do=["CLEAN_THREE_WAY"], severity="HIGH", description="Invoice unit price above PO"),
    _c(discrepancy_id="AP-DISC-003", domain="ap", type="missing_goods_receipt", source_ids=["INV-005", "PO-108"], expected_detection="missing_gr", expected_disposition="HOLD", expected_status="HOLD", allowed_reason_codes=["goods_not_received"], must_not_do=["FABRICATE_RECEIPT", "CLEAN_THREE_WAY"], severity="HIGH", description="PO and invoice with no GR"),
    _c(discrepancy_id="AP-DISC-004", domain="ap", type="duplicate_invoice", source_ids=["INV-006", "INV-007"], expected_detection="duplicate", expected_disposition="HOLD", expected_status="HOLD", allowed_reason_codes=["duplicate"], must_not_do=["APPROVE_DUPLICATE"], severity="BLOCKING", description="Same vendor invoice number twice"),
    _c(discrepancy_id="AP-DISC-005", domain="ap", type="normalized_duplicate", source_ids=["INV-DISC-1048A", "INV-DISC-1048B"], expected_detection="duplicate", expected_disposition="HOLD", expected_status="HOLD", allowed_reason_codes=["duplicate"], severity="HIGH", description="INV-1048 vs INV 1048 after normalization"),
    _c(discrepancy_id="AP-DISC-006", domain="ap", type="approval_threshold", source_ids=["INV-009", "PO-109"], expected_detection="approval_limit", expected_disposition="HOLD", expected_status="HOLD", allowed_reason_codes=["approval_limit_exceeded"], must_not_do=["APPROVE"], severity="HIGH", description="PO exceeds approver limit"),
    _c(discrepancy_id="AP-DISC-007", domain="ap", type="self_approval", source_ids=["APR-INV-SELF"], expected_detection="self_approval", expected_disposition="FAIL", expected_status="FAIL", allowed_reason_codes=["SELF_APPROVAL"], severity="HIGH", description="Requester equals approver"),
    _c(discrepancy_id="AP-DISC-008", domain="ap", type="pay_while_held", source_ids=["INV-010"], expected_detection="held_not_payable", expected_disposition="BLOCK_PAYMENT", expected_status="INELIGIBLE", allowed_reason_codes=["goods_not_received"], must_not_do=["SILENT_RELEASE"], severity="BLOCKING", description="Held invoice must not enter the payment pool"),
    _c(discrepancy_id="AR-DISC-001", domain="ar", type="partial_payment", source_ids=["PAY-DISC-PARTIAL", "INV-DISC-PARTIAL"], expected_detection="partial", expected_disposition="AUTO_APPLY", expected_status="PARTIALLY_APPLIED", expected_amount_cents=960000, must_not_do=["MARK_FULLY_PAID"], severity="MEDIUM", description="$10,000 invoice vs $9,600 remittance"),
    _c(discrepancy_id="AR-DISC-002", domain="ar", type="overpayment", source_ids=["PAY-DISC-OVER", "INV-DISC-OVER"], expected_detection="overpayment", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", expected_amount_cents=75000, must_not_do=["DROP_RESIDUAL"], severity="HIGH", description="$8,000 invoice vs $8,750 payment"),
    _c(discrepancy_id="AR-DISC-003", domain="ar", type="ambiguous_remittance", source_ids=["PAY-004", "INV-AR-010", "INV-AR-011"], expected_detection="ambiguity", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", must_not_do=["UNSAFE_AUTO_APPLY"], severity="HIGH", description="Two $5,000 invoices, no unique reference"),
    _c(discrepancy_id="AR-DISC-004", domain="ar", type="invalid_invoice_ref", source_ids=["PAY-DISC-BADREF"], expected_detection="invalid_reference", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", allowed_reason_codes=["INVALID_REFERENCE"], severity="MEDIUM", description="Remittance cites AR-INV-9999"),
    _c(discrepancy_id="AR-DISC-005", domain="ar", type="customer_identity", source_ids=["PAY-DISC-ID"], expected_detection="identity_conflict", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", severity="HIGH", description="Remittance customer conflicts with bank sender"),
    _c(discrepancy_id="AR-DISC-006", domain="ar", type="double_application", source_ids=["PAY-DISC-DOUBLE"], expected_detection="already_applied", expected_disposition="UNAPPLIED", expected_status="UNAPPLIED", must_not_do=["DOUBLE_APPLY"], severity="HIGH", description="Second apply of an already-posted payment"),
    _c(discrepancy_id="CASH-DISC-001", domain="cash", type="unexplained_difference", source_ids=["TXN-2026-09-015"], expected_detection="unexplained", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", expected_amount_cents=1240, allowed_reason_codes=["UNEXPLAINED_DIFFERENCE"], must_not_do=["FORCE_MATCH", "INVENT_FEE", "MARK_RECONCILED"], severity="BLOCKING", downstream_impact="Blocks month-end cash task", description="$12.40 unexplained bank vs ledger"),
    _c(discrepancy_id="CASH-DISC-002", domain="cash", type="duplicate_refund", source_ids=["TXN-2026-09-012B"], expected_detection="duplicate_refund", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", allowed_reason_codes=["POSSIBLE_DUPLICATE_REFUND"], severity="HIGH", description="Refund posted twice"),
    _c(discrepancy_id="CASH-DISC-003", domain="cash", type="fee_missing_ledger", source_ids=["TXN-2026-09-011", "FEE-729103"], expected_detection="fee", expected_disposition="EXPLAINED_EXCEPTION", expected_status="FEE_NETTED", allowed_reason_codes=["FEE_NETTED"], severity="MEDIUM", description="Wire net of known $25 bank fee"),
    _c(discrepancy_id="CASH-DISC-004", domain="cash", type="grouped_residual", source_ids=["TXN-DISC-GRP"], expected_detection="grouped_residual", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", expected_amount_cents=15000, must_not_do=["FORCE_GROUPED_MATCH"], severity="HIGH", description="$6,000 invoices vs $5,850 bank"),
    _c(discrepancy_id="CASH-DISC-005", domain="cash", type="ledger_only", source_ids=["GL-AP-ORPHAN"], expected_detection="unmatched_ledger", expected_disposition="HUMAN_REVIEW", expected_status="UNMATCHED_LEDGER", severity="MEDIUM", description="Ledger payment missing from bank"),
    _c(discrepancy_id="CASH-DISC-006", domain="cash", type="bank_only", source_ids=["TXN-2026-09-025"], expected_detection="unmatched_bank", expected_disposition="HUMAN_REVIEW", expected_status="UNMATCHED_BANK", severity="MEDIUM", description="Bank item with no ledger candidate"),
    _c(discrepancy_id="CASH-DISC-007", domain="cash", type="stripe_mismatch", source_ids=["TXN-DISC-STRIPE"], expected_detection="payout_mismatch", expected_disposition="HUMAN_REVIEW", expected_status="HUMAN_REVIEW", must_not_do=["MARK_RECONCILED"], severity="HIGH", description="Stripe payout does not equal charges minus fees/refunds"),
    _c(discrepancy_id="CLOSE-DISC-001", domain="close", type="ap_gl_mismatch", source_ids=["GL-AP-DISC"], expected_detection="ap_tie_break", expected_disposition="BLOCKED", expected_status="BLOCKED", severity="BLOCKING", description="AP subledger does not tie to GL"),
    _c(discrepancy_id="CLOSE-DISC-002", domain="close", type="ar_gl_mismatch", source_ids=["GL-AR-DISC"], expected_detection="ar_tie_break", expected_disposition="BLOCKED", expected_status="BLOCKED", severity="BLOCKING", description="AR subledger does not tie to GL"),
    _c(discrepancy_id="CLOSE-DISC-003", domain="close", type="unresolved_bank_recon", source_ids=["TXN-2026-09-015"], expected_detection="cash_blocked", expected_disposition="BLOCKED", expected_status="BLOCKED", severity="BLOCKING", downstream_impact="Period cannot close", description="Inherit $12.40 cash break"),
    _c(discrepancy_id="CLOSE-DISC-004", domain="close", type="missing_accrual", source_ids=["ACC-HE-2026-09"], expected_detection="accrue", expected_disposition="ACCRUE", expected_status="IDENTIFIED", severity="HIGH", description="Harbor Electric incurred, no invoice"),
    _c(discrepancy_id="CLOSE-DISC-005", domain="close", type="prepaid_amortization", source_ids=["PRE-SFT-001"], expected_detection="prepaid_variance", expected_disposition="NEEDS_REVIEW", expected_status="OPEN", expected_amount_cents=20000, severity="HIGH", description="$1,200 posted vs $1,000 expected"),
    _c(discrepancy_id="CLOSE-DISC-006", domain="close", type="depreciation_variance", source_ids=["FA-DELL-001"], expected_detection="fa_variance", expected_disposition="NEEDS_REVIEW", expected_status="OPEN", severity="MEDIUM", description="GL depreciation differs from schedule"),
    _c(discrepancy_id="CLOSE-DISC-007", domain="close", type="unsupported_balance", source_ids=["GL-UNSUP-001"], expected_detection="missing_evidence", expected_disposition="NEEDS_REVIEW", expected_status="OPEN", severity="HIGH", description="GL balance with no support"),
    _c(discrepancy_id="AUDIT-DISC-001", domain="audit", type="duplicate_vendor", source_ids=["VEND-001", "VEND-001-DUP"], expected_detection="duplicate_vendor", expected_disposition="FAIL", expected_status="FAIL", allowed_reason_codes=["DUPLICATE_VENDOR"], severity="HIGH", description="Vendors normalize to the same party"),
    _c(discrepancy_id="AUDIT-DISC-002", domain="audit", type="round_number", source_ids=["PAY-AP-009"], expected_detection="round_number", expected_disposition="FAIL", expected_status="FAIL", allowed_reason_codes=["ROUND_NUMBER"], severity="HIGH", description="$50,000 round payment"),
    _c(discrepancy_id="AUDIT-DISC-003", domain="audit", type="post_close_je", source_ids=["JE-POST-CLOSE-001"], expected_detection="post_close", expected_disposition="FAIL", expected_status="FAIL", allowed_reason_codes=["UNAUTHORIZED_POST_CLOSE_ENTRY"], severity="HIGH", description="Journal posted after close"),
    _c(discrepancy_id="AUDIT-DISC-004", domain="audit", type="self_approval", source_ids=["APR-INV-SELF"], expected_detection="self_approval", expected_disposition="FAIL", expected_status="FAIL", allowed_reason_codes=["SELF_APPROVAL"], severity="HIGH", description="Same person requested and approved"),
    _c(discrepancy_id="AUDIT-DISC-005", domain="audit", type="missing_support", source_ids=["PAY-AP-009"], expected_detection="missing_evidence", expected_disposition="FAIL", expected_status="FAIL", severity="MEDIUM", description="Sampled payment missing support"),
    _c(discrepancy_id="AUDIT-DISC-006", domain="audit", type="bad_recon_conclusion", source_ids=["REC-NS-1240", "TXN-2026-09-015"], expected_detection="reperformance_disagree", expected_disposition="FAIL", expected_status="FAIL", severity="BLOCKING", description="Prior recon said reconciled; $12.40 remains"),
    _c(discrepancy_id="AUDIT-DISC-007", domain="audit", type="threshold", source_ids=["INV-009", "PO-109"], expected_detection="threshold", expected_disposition="FAIL", expected_status="FAIL", severity="HIGH", description="Approval exceeds authorized level"),
    _c(discrepancy_id="REPORT-DISC-001", domain="reporting", type="board_vs_gl", source_ids=["4000-Revenue"], expected_detection="gl_tie", expected_disposition="USE_GL", expected_status="CORRECTED", expected_amount_cents=100000000, must_not_do=["PUBLISH_DRAFT"], severity="BLOCKING", description="Draft board revenue must lose to GL"),
    _c(discrepancy_id="REPORT-DISC-002", domain="reporting", type="unsupported_narrative", source_ids=["TXN-REV-SEP-001"], expected_detection="reject_narrative", expected_disposition="REJECT", expected_status="UNSUPPORTED", severity="HIGH", description="Supplier-cost story vs discounting drivers"),
    _c(discrepancy_id="REPORT-DISC-003", domain="reporting", type="missing_contributor", source_ids=["TXN-REV-SEP-001"], expected_detection="incomplete_variance", expected_disposition="INCOMPLETE", expected_status="OPEN", severity="HIGH", description="Explained variance omits a major driver"),
    _c(discrepancy_id="REPORT-DISC-004", domain="reporting", type="wrong_period", source_ids=["TXN-DISC-OCT"], expected_detection="period_error", expected_disposition="EXCLUDE", expected_status="EXCLUDED", must_not_do=["INCLUDE_OCTOBER"], severity="HIGH", description="October txn must not hit September P&L"),
    _c(discrepancy_id="FORECAST-DISC-001", domain="forecasting", type="early_ar_receipt", source_ids=["INV-DISC-FC-AR"], expected_detection="timing_flag", expected_disposition="FLAG", expected_status="OPEN", severity="MEDIUM", description="Receipt forecasted weeks before due date"),
    _c(discrepancy_id="FORECAST-DISC-002", domain="forecasting", type="missing_ap_outflow", source_ids=["INV-002"], expected_detection="coverage_gap", expected_disposition="FLAG", expected_status="OPEN", severity="HIGH", description="Approved payable omitted from forecast"),
    _c(discrepancy_id="FORECAST-DISC-003", domain="forecasting", type="duplicate_outflow", source_ids=["INV-DISC-FC-DUP"], expected_detection="duplicate_outflow", expected_disposition="FLAG", expected_status="OPEN", severity="HIGH", description="Same AP payment appears twice"),
    _c(discrepancy_id="FORECAST-DISC-004", domain="forecasting", type="opening_cash", source_ids=["FC-OPEN"], expected_detection="opening_mismatch", expected_disposition="FLAG", expected_status="OPEN", severity="BLOCKING", description="Opening cash != prior ending actual"),
    _c(discrepancy_id="FORECAST-DISC-005", domain="forecasting", type="untraceable_actual", source_ids=["ACT-DISC-NOSRC"], expected_detection="unsupported_source", expected_disposition="FLAG", expected_status="OPEN", severity="HIGH", description="Actual with no bank/ledger source"),
    _c(discrepancy_id="FORECAST-DISC-006", domain="forecasting", type="wrong_miss_story", source_ids=["INV-AR-014"], expected_detection="source_tied_miss", expected_disposition="CORRECT", expected_status="TIED", must_not_do=["ACCEPT_PAYROLL_STORY"], severity="HIGH", description="Miss is late AR, not higher payroll"),
    _c(discrepancy_id="XFUNC-DISC-001", domain="cross_function", type="held_but_paid", source_ids=["INV-010", "PAY-AP-010"], expected_detection="policy_contradiction", expected_disposition="FAIL", expected_status="FAIL", severity="BLOCKING", description="AP hold but bank payment occurred"),
    _c(discrepancy_id="XFUNC-DISC-002", domain="cross_function", type="cash_open_close_complete", source_ids=["TXN-2026-09-015"], expected_detection="close_rejects", expected_disposition="BLOCKED", expected_status="BLOCKED", severity="BLOCKING", description="Close must not complete while $12.40 is open"),
    _c(discrepancy_id="XFUNC-DISC-003", domain="cross_function", type="ar_vs_gl_settled", source_ids=["INV-DISC-SETTLE"], expected_detection="subledger_gl", expected_disposition="OPEN", expected_status="OPEN", severity="BLOCKING", description="AR open, GL settled"),
    _c(discrepancy_id="XFUNC-DISC-004", domain="cross_function", type="forecast_vs_bank", source_ids=["INV-DISC-FC-PAY"], expected_detection="missing_bank_actual", expected_disposition="FLAG", expected_status="OPEN", severity="HIGH", description="Forecast says paid; bank has no payment"),
    _c(discrepancy_id="XFUNC-DISC-005", domain="cross_function", type="rejected_in_reporting", source_ids=["TXN-2026-09-015"], expected_detection="respect_close", expected_disposition="NOT_RECONCILED", expected_status="OPEN", must_not_do=["CLAIM_RECONCILED"], severity="HIGH", description="Reporting must not claim cash is reconciled"),
]


def contracts() -> list[DiscrepancyContract]:
    return [item.model_copy() for item in CONTRACTS]


def contracts_by_id() -> dict[str, DiscrepancyContract]:
    return {item.discrepancy_id: item for item in CONTRACTS}
