"""Machine-readable inventory of the live Office-of-the-CFO system.

This updates the existing skill registry rather than creating a second one.
Assignments stay in ``skills/assignments.py`` / ``skills/README.md``.
"""

from __future__ import annotations

from skills.assignments import AGENT_SKILLS, catalog as skill_catalog
from skills.loader import list_skill_names


CAPABILITIES = [
    {
        "capability_id": "inbox.counterparty_to_ap",
        "name": "Gmail-like finance inbox with two-agent handoff",
        "agents": ["Counterparty Message Agent", "Finance Inbox Agent"],
        "skills": [
            "inbox-triage",
            "invoice-source-identification",
            "invoice-field-interpretation",
        ],
        "workflow": "inbox.workflow.handoff",
        "entrypoint": "python main.py demo-inbox",
        "required_inputs": ["message envelope", "optional attachment"],
        "expected_outputs": [
            "classification",
            "registered action",
            "canonical AP invoice or structured notice",
            "trace",
        ],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-INBOX-{n:03d}" for n in range(1, 19)],
    },
    {
        "capability_id": "ingestion.classify_document",
        "name": "Invoice / document classification",
        "agents": [
            "Email Invoice Agent",
            "Vendor Portal Agent",
            "Employee Submission Agent",
            "Physical Mail / Document Agent",
            "Procurement Invoice Agent",
        ],
        "skills": ["invoice-source-identification", "invoice-field-interpretation"],
        "workflow": "invoice_ingestion.workflow.ingest_invoices",
        "entrypoint": "python main.py ingest 2026-09",
        "required_inputs": ["source record", "subject/filename/text"],
        "expected_outputs": ["classification", "extracted fields", "canonical invoice identity"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-ING-{n:03d}" for n in range(1, 11)] + ["SCN-AP-012"],
    },
    {
        "capability_id": "ingestion.structured_parse",
        "name": "Structured ERP / Coupa / EDI parse",
        "agents": ["ERP Invoice Agent", "EDI / Electronic Invoicing Agent"],
        "skills": [],
        "workflow": "invoice_ingestion.sources",
        "entrypoint": "python -m invoice_ingestion.demo",
        "required_inputs": ["erp.json / edi_documents.json"],
        "expected_outputs": ["InvoiceCandidate"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-ING-001", "SCN-ING-010"],
    },
    {
        "capability_id": "ingestion.bank_card_discovery",
        "name": "Recover invoice from a bank/card charge only with supporting docs",
        "agents": ["Bank/Card Discovery Agent"],
        "skills": ["bank-charge-invoice-discovery"],
        "workflow": "invoice_ingestion.sources",
        "entrypoint": "python main.py ingest 2026-09",
        "required_inputs": ["bank/card charge", "supporting documents"],
        "expected_outputs": ["invoice_found | invoice_missing"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-AP-012"],
    },
    {
        "capability_id": "ap.three_way_match",
        "name": "Three-way match and AP approve/hold",
        "agents": ["AP Preparer", "Exception Investigator", "AP Reviewer", "AP Approver", "AP Audit"],
        "skills": ["three-way-match-analysis", "ap-exception-investigation"],
        "workflow": "workflow.run_ap_workflow",
        "entrypoint": "python main.py INV-001",
        "required_inputs": ["invoice_id", "PO", "goods receipt", "policies", "prior_cases"],
        "expected_outputs": ["APPROVE | HOLD", "exception types", "evidence"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-AP-{n:03d}" for n in range(1, 9)] + ["SCN-AP-013"],
    },
    {
        "capability_id": "ap.payment_scheduling",
        "name": "Weekly payment prioritization",
        "agents": ["Payment Scheduler", "Payment Audit"],
        "skills": ["payment-prioritization", "early-payment-discount-evaluation"],
        "workflow": "scheduling.workflow.run_schedule_workflow",
        "entrypoint": "python main.py schedule --seed-demo",
        "required_inputs": ["approved_pool", "cash_position"],
        "expected_outputs": ["pay_this_week", "defer", "metrics"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-AP-009", "SCN-AP-010", "SCN-AP-011"],
    },
    {
        "capability_id": "ar.aging_collections",
        "name": "AR aging and collections",
        "agents": ["Collections Agent"],
        "skills": ["ar-collections-policy"],
        "workflow": "ar.workflow.run_aging / run_collections",
        "entrypoint": "python main.py ar-aging --as-of 2026-09-30",
        "required_inputs": ["ar_invoices", "as_of_date"],
        "expected_outputs": ["aging bucket", "collection action"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-AR-{n:03d}" for n in range(1, 6)] + ["SCN-AR-012"],
    },
    {
        "capability_id": "ar.cash_application",
        "name": "Cash application including ambiguous remittances",
        "agents": ["Cash Application Agent", "Cash Application Reviewer"],
        "skills": ["cash-application"],
        "workflow": "ar.workflow.run_cash_apply",
        "entrypoint": "python main.py ar-cash-apply PAY-001",
        "required_inputs": ["payment_id", "open invoices", "precedents"],
        "expected_outputs": ["AUTO_APPLY | HUMAN_REVIEW | UNAPPLIED", "selected invoices"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-AR-006", "SCN-AR-007", "SCN-AR-008", "SCN-AR-009", "SCN-AR-010", "SCN-AR-011", "SCN-AR-013"],
    },
    {
        "capability_id": "cash.bank_reconciliation",
        "name": "Bank / cash ledger reconciliation",
        "agents": [
            "Cash Reconciliation Preparer",
            "Cash Exception Investigator",
            "Cash Reconciliation Reviewer",
        ],
        "skills": [
            "cash-reconciliation-method-selection",
            "reconciliation-exception-investigation",
            "bank-reference-interpretation",
        ],
        "workflow": "cash_recon.workflow.run_cash_reconciliation",
        "entrypoint": "python main.py reconcile-cash --month 2026-09 --seed-demo",
        "required_inputs": ["bank_statement", "cash ledger", "fee evidence"],
        "expected_outputs": ["MATCHED | EXPLAINED_EXCEPTION | HUMAN_REVIEW | OUTSTANDING_TIMING_ITEM"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-CASH-{n:03d}" for n in range(1, 13)],
    },
    {
        "capability_id": "cash.stripe_reconciliation",
        "name": "Stripe payout reconciliation",
        "agents": ["Cash Reconciliation Preparer"],
        "skills": ["cash-reconciliation-method-selection"],
        "workflow": "integrations.cash.reconcile_payout + cash_recon",
        "entrypoint": "python main.py stripe-demo",
        "required_inputs": ["stripe payouts", "balance transactions", "bank deposit"],
        "expected_outputs": ["PROVIDER_PAYOUT", "tied payout arithmetic"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CASH-009", "SCN-CASH-010", "SCN-CASH-011"],
    },
    {
        "capability_id": "close.accruals",
        "name": "Missing-bill accruals",
        "agents": ["Accrual Agent"],
        "skills": ["accrual-evidence-evaluation", "accrual-method-selection"],
        "workflow": "accrual.workflow.run_accrual_workflow",
        "entrypoint": "python accrue.py 2026-09",
        "required_inputs": ["historical invoices", "contracts", "usage", "POs"],
        "expected_outputs": ["ACCRUE | SKIP | INSUFFICIENT_EVIDENCE", "JE"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CLOSE-001", "SCN-CLOSE-002", "SCN-MEM-004"],
    },
    {
        "capability_id": "close.prepaids",
        "name": "Prepaid amortization",
        "agents": ["Prepaid Preparer", "Prepaid Reviewer"],
        "skills": ["prepaid-expense-accounting"],
        "workflow": "prepaid.workflow.run_prepaid_workflow",
        "entrypoint": "python close.py prepaid --period 2026-09",
        "required_inputs": ["prepaid item", "service period"],
        "expected_outputs": ["schedule", "monthly JE", "remaining balance"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CLOSE-003", "SCN-CLOSE-004", "SCN-CLOSE-009"],
    },
    {
        "capability_id": "close.fixed_assets",
        "name": "Fixed-asset depreciation",
        "agents": ["Fixed Asset Preparer", "Fixed Asset Reviewer"],
        "skills": ["fixed-asset-depreciation"],
        "workflow": "fixed_assets.workflow.run_depreciation_workflow",
        "entrypoint": "python close.py depreciate --period 2026-09",
        "required_inputs": ["capital invoice / asset register"],
        "expected_outputs": ["straight-line schedule", "NBV", "JE"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CLOSE-005"],
    },
    {
        "capability_id": "close.balance_sheet_recs",
        "name": "Balance-sheet substantiation",
        "agents": ["Balance Sheet Reconciliation Preparer", "Balance Sheet Reconciliation Reviewer"],
        "skills": ["balance-sheet-reconciliation"],
        "workflow": "bs_recon.workflow.run_balance_sheet_reconciliations",
        "entrypoint": "python main.py close 2026-09",
        "required_inputs": ["ledger balances", "subledger evidence"],
        "expected_outputs": ["tie / exception / needs review"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CLOSE-007", "SCN-CLOSE-008", "SCN-CLOSE-009", "SCN-CLOSE-010"],
    },
    {
        "capability_id": "close.month_end",
        "name": "Month-end close coordination and gating",
        "agents": ["Month-End Close Reviewer", "Close Manager"],
        "skills": ["month-end-close-review", "month-end-close-coordination"],
        "workflow": "close.month_end.run_month_end",
        "entrypoint": "python main.py demo-close",
        "required_inputs": ["AP/AR/cash/accrual/prepaid/asset task statuses"],
        "expected_outputs": ["BLOCKED | CLOSED", "blockers"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CLOSE-011", "SCN-CLOSE-012", "SCN-CLOSE-013", "SCN-CLOSE-015", "SCN-CLOSE-016", "SCN-CFO-001"],
        "notes": "Close Manager SDK agent is defined; production coordination uses deterministic_coordinate().",
    },
    {
        "capability_id": "audit.controls",
        "name": "Independent audit sampling and control testing",
        "agents": ["Auditor Agent", "Audit Report Agent"],
        "skills": [
            "audit-sampling-interpretation",
            "control-testing-interpretation",
            "reconciliation-reperformance-review",
            "segregation-of-duties-interpretation",
            "audit-finding-writing",
        ],
        "workflow": "audit.workflow.run_audit",
        "entrypoint": "python main.py audit --period 2026-09 --seed 26",
        "required_inputs": ["operational populations", "planted exceptions"],
        "expected_outputs": ["findings", "samples", "reperformance"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-AUDIT-{n:03d}" for n in range(1, 14)],
    },
    {
        "capability_id": "reporting.variance_board",
        "name": "Variance analysis and board reporting",
        "agents": ["Variance Analysis Agent", "Reporting Reviewer Agent", "Board Reporting Agent"],
        "skills": ["financial-variance-analysis", "board-financial-reporting"],
        "workflow": "reporting.workflow.run_reporting_workflow",
        "entrypoint": "python main.py demo-reporting",
        "required_inputs": ["reporting ledger", "comparison period"],
        "expected_outputs": ["statements", "variance drivers", "board pack"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-REPORT-001", "SCN-REPORT-002"],
    },
    {
        "capability_id": "forecast.thirteen_week",
        "name": "13-week cash forecast and forecast-vs-actual",
        "agents": ["Cash Forecast Agent", "Forecast Reviewer Agent", "Forecast Variance Agent"],
        "skills": ["cash-forecasting", "ar-cash-forecasting", "forecast-vs-actual-interpretation"],
        "workflow": "reporting.forecast / reporting.workflow",
        "entrypoint": "python main.py cash-forecast --as-of 2026-09-30 --weeks 13",
        "required_inputs": ["AP pool", "AR invoices", "payroll", "opening cash"],
        "expected_outputs": ["13 weeks", "miss drivers"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [f"SCN-REPORT-{n:03d}" for n in range(3, 9)] + ["SCN-CFO-002"],
    },
    {
        "capability_id": "memory.cross_period",
        "name": "Cross-period precedent retrieval",
        "agents": [
            "Exception Investigator",
            "Cash Exception Investigator",
            "Prepaid Preparer",
            "Cash Application Agent",
        ],
        "skills": ["prior-period-precedent", "ap-exception-investigation", "cash-application"],
        "workflow": "memory.store / cash_recon.workflow / prepaid.workflow / tools.get_prior_cases",
        "entrypoint": "python main.py memory-demo --story stripe",
        "required_inputs": ["prior decision memory", "current-period evidence"],
        "expected_outputs": ["retrieved decision_id", "precedent_used on later-period trace"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-MEM-001", "SCN-MEM-002", "SCN-MEM-003", "SCN-MEM-004"],
    },
    {
        "capability_id": "memory.self_improvement",
        "name": "Learn from structured correction",
        "agents": ["Cash Application Reviewer"],
        "skills": ["cash-application"],
        "workflow": "ar.ledger.record_human_application",
        "entrypoint": "python main.py ar-review-correct PAY-005 ...",
        "required_inputs": ["human correction"],
        "expected_outputs": ["updated precedent", "later retrieval"],
        "status": "PARTIALLY_IMPLEMENTED",
        "scenario_ids": ["SCN-LEARN-001"],
        "notes": "AR writes human-sourced precedents. AP prior_cases are static seed and are not appended from new decisions.",
    },
    {
        "capability_id": "orchestration.cfo",
        "name": "Whole-company CFO orchestration",
        "agents": ["Close Manager", "Month-End Close Reviewer"],
        "skills": ["month-end-close-coordination"],
        "workflow": "cfo.scenario.run_cfo_scenario",
        "entrypoint": "python main.py cfo-demo",
        "required_inputs": ["broad objective / period"],
        "expected_outputs": ["internally consistent close + cash + reporting result"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": ["SCN-CFO-001", "SCN-CFO-002", "SCN-HAND-001", "SCN-HAND-002"],
    },
    {
        "capability_id": "sample_data.generation",
        "name": "Synthetic company generation",
        "agents": [
            "AP/AR Sample Data Agent",
            "Cash Recon Sample Data Agent",
            "Close Sample Data Agent",
            "Audit Controls Sample Data Agent",
            "Reporting Forecasting Sample Data Agent",
        ],
        "skills": ["synthetic-finance-scenario-design", "cross-ledger-data-consistency"],
        "workflow": "sample_data.orchestrator.generate_sample_data",
        "entrypoint": "python main.py generate-sample-data --seed 42 --month 2026-09 --output data/demo",
        "required_inputs": ["seed", "period"],
        "expected_outputs": ["data/demo pack", "manifest", "expected_results"],
        "status": "IMPLEMENTED_AND_TESTED",
        "scenario_ids": [],
    },
]


ENTRYPOINTS = [
    {"command": "python main.py INV-001", "workflow": "run_ap_workflow", "mutates": "approved_pool + AP trace"},
    {"command": "python main.py schedule --seed-demo", "workflow": "run_schedule_workflow", "mutates": "schedule trace only"},
    {"command": "python main.py ingest 2026-09", "workflow": "ingest_invoices", "mutates": "in-memory canonical registry"},
    {"command": "python main.py demo-inbox", "workflow": "inbox.workflow.handoff", "mutates": "inbox traces + AP overlay"},
    {"command": "python main.py accrue 2026-09", "workflow": "run_accrual_workflow", "mutates": "accrual journals"},
    {"command": "python main.py ar-aging --as-of 2026-09-30", "workflow": "run_aging", "mutates": "runs/ar state"},
    {"command": "python main.py ar-collections --as-of 2026-09-30", "workflow": "run_collections", "mutates": "runs/ar traces"},
    {"command": "python main.py ar-cash-apply PAY-001", "workflow": "run_cash_apply", "mutates": "AR balances"},
    {"command": "python main.py reconcile-cash --month 2026-09 --seed-demo", "workflow": "run_cash_reconciliation", "mutates": "cash traces"},
    {"command": "python main.py demo-close", "workflow": "run_month_end", "mutates": "month_end state + journals"},
    {"command": "python main.py audit --period 2026-09 --seed 26", "workflow": "run_audit", "mutates": "audit run artifacts"},
    {"command": "python main.py demo-reporting", "workflow": "run_reporting_workflow", "mutates": "reporting snapshots"},
    {"command": "python main.py cash-forecast --as-of 2026-09-30 --weeks 13", "workflow": "reporting cash forecast", "mutates": "forecast snapshots"},
    {"command": "python main.py cfo-demo", "workflow": "run_cfo_scenario", "mutates": "shared close/AR/cash/reporting state"},
    {"command": "python main.py generate-sample-data --output data/demo", "workflow": "generate_sample_data", "mutates": "data/demo canonical pack"},
    {"command": "python main.py evaluate-cfo --data-root data/demo --all", "workflow": "CFOEvaluationRunner", "mutates": "runs/evaluation only"},
    {"command": "python -m evals.demo_company", "workflow": "run_demo_company_eval", "mutates": "runs/demo_eval only"},
    {"command": "python main.py memory-demo --story stripe", "workflow": "memory.scenarios.run_stripe_cross_period", "mutates": "runs/memory/decisions.json + cash traces"},
    {"command": "python main.py eval-memory", "workflow": "memory.eval.run_memory_evaluation", "mutates": "runs/memory_eval only"},
]


TOOLS = {
    "tools.py": [
        "get_invoice",
        "get_purchase_order",
        "get_goods_receipt",
        "find_duplicate_invoices",
        "get_case_evidence",
        "get_company_policies",
        "find_relevant_policies",
        "get_prior_cases",
        "get_decision_memories",
    ],
    "ar/tools.py": [
        "get_collection_candidates",
        "get_collection_invoice_facts",
        "get_cash_application_facts",
        "get_ar_precedents",
        "get_ar_customer",
        "get_ar_close_snapshot",
    ],
    "accrual/tools.py": [
        "get_expected_invoices",
        "get_estimate_candidates",
        "create_accrual",
        "reconcile_accrual_with_invoice",
    ],
    "cash_recon/tools.py": [
        "get_bank_transaction",
        "get_ledger_entry",
        "get_fee_evidence",
        "get_match_candidates",
        "get_candidate",
        "get_decision_memories",
    ],
    "scheduling/tools.py": ["get_cash_position", "get_approved_pool", "get_payment_candidates", "get_treasury_policies"],
    "prepaid/tools.py": ["get_prepaid", "list_prepaids", "get_prepaid_treatment_candidates", "get_prepaid_schedule", "get_decision_memories"],
    "fixed_assets/tools.py": ["get_fixed_asset", "list_fixed_assets", "get_depreciation_schedule", "get_capital_candidates"],
    "bs_recon/tools.py": ["get_reconciliation_packet", "list_reconciling_items", "list_period_reconciliations"],
    "audit/tools.py": ["get_audit_period", "get_audit_payments", "get_audit_journals", "get_operational_decisions"],
    "reporting/tools.py": ["get_period_metrics", "get_variance_facts", "get_cash_forecast", "get_forecast_snapshot"],
    "invoice_ingestion/tools.py": ["list/get source records", "find_related_invoice"],
    "inbox/tools.py": [
        "compose_counterparty_message",
        "send_inbox_message",
        "reply_in_thread",
        "get_inbox_message",
        "classify_inbox_message",
        "dispatch_inbox_action",
    ],
}


def build_system_capabilities() -> dict:
    agents = []
    for name, skills in AGENT_SKILLS.items():
        related = [item for item in CAPABILITIES if name in item["agents"]]
        agents.append(
            {
                "agent": name,
                "skills": list(skills),
                "functionalities": [item["capability_id"] for item in related],
                "required_inputs": sorted({inp for item in related for inp in item["required_inputs"]}),
                "expected_outputs": sorted({out for item in related for out in item["expected_outputs"]}),
                "workflows": sorted({item["workflow"] for item in related}),
                "entrypoints": sorted({item["entrypoint"] for item in related}),
            }
        )
    return {
        "company": "Maximor Demo Corp",
        "schema_version": "2026.09-cfo-demo-capabilities-1",
        "skill_registry": "skills/README.md",
        "skill_assignments": "skills/assignments.py",
        "agents": agents,
        "skills": skill_catalog(),
        "skill_names": list_skill_names(),
        "capabilities": CAPABILITIES,
        "tools": TOOLS,
        "entrypoints": ENTRYPOINTS,
        "persistence": {
            "canonical_demo": "data/demo",
            "runtime_copy": "runs/demo_runtime",
            "eval_runs": "runs/demo_eval",
            "operational_runs": ["runs/ar", "runs/month_end", "runs/cash_recon", "runs/audit", "runs/reporting", "runs/inbox"],
            "memory": [
                "runs/memory/decisions.json",
                "data/demo/prior_cases.json",
                "data/demo/ar_precedents.json",
                "data/demo/memory_events.json",
            ],
        },
        "memory_mechanisms": {
            "prior_cases": "Static AP seed; read by investigator/reviewer/approver. Not appended from new AP decisions.",
            "ar_precedents": "Seed plus human corrections via ar.ledger._learn_precedent.",
            "decision_memory": "Canonical cross-period DecisionMemory in runs/memory/decisions.json. Written after reusable cash, prepaid, and AP exception decisions; retrieved by structured match before later-period decisions.",
            "identity_links": "close/context provenance, not a semantic graph DB.",
            "self_improvement": "PARTIAL — AR human corrections plus organizational decision memory writes.",
        },
        "integrations": ["stripe", "adyen", "gmail", "outlook", "xero", "coupa", "netsuite"],
        "mutating_workflows": [
            "run_ap_workflow (pool on APPROVE)",
            "ingest_invoices (in-memory registry)",
            "run_accrual_workflow / create_accrual",
            "run_cash_apply / record_human_application",
            "run_month_end / prepaid / depreciation / post_journal",
            "run_cash_reconciliation (traces; proposed journals not auto-posted)",
            "run_audit (audit artifacts only)",
        ],
    }
